### ISSUE TITLE
Re-structure the repo and change name

### ISSUE THREAD

**Issue by dachafra** [kg-construct/rml-fnml#20]
New structure:
- [x] folder `spec` with all the resources for the specification (the current content of the repo)
- [x] folder `ontology`, which I think is coming from #15 
- [x] folder `shapes`, coming from #18 
- [x] folder `test-cases`, for #19 

Other changes:
- [x] The new name of the repo should be: `rml-fnml`

**Comment by bjdmeest** [comment]
Done in development branch
